name: AccTest Command

on:
  issue_comment:
    types: [created]

jobs:
  acctest-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # PAT or OAuth token will also work
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: acctest
          named-args: true
          permission: write
